version: '3.7'

services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wp

  mailhog:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8080:80"
    depends_on:
    - mariadb

  mailhog:
    image: mailhog/mailhog
    ports:
      - "80:80"
    depends_on:
    - mariadb