version: '3.7'

services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mag

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - "8085:80"
    depends_on:
    - mariadb

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:80"
      - "8025:80"
    depends_on:
    - mariadb

 